/* tslint:disable */
/* eslint-disable */
/**
 * NodeLabs API
 * A production-ready, fully modular Node.js Express boilerplate.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface FinancialSummaryTotalBalanceChange {
    'percentage'?: number;
    'trend'?: FinancialSummaryTotalBalanceChangeTrendEnum;
}

export const FinancialSummaryTotalBalanceChangeTrendEnum = {
    Up: 'up',
    Down: 'down',
    Stable: 'stable'
} as const;

export type FinancialSummaryTotalBalanceChangeTrendEnum = typeof FinancialSummaryTotalBalanceChangeTrendEnum[keyof typeof FinancialSummaryTotalBalanceChangeTrendEnum];


