/* tslint:disable */
/* eslint-disable */
/**
 * NodeLabs API
 * A production-ready, fully modular Node.js Express boilerplate.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RecentTransactionsSummary } from './recent-transactions-summary';
// May contain unused imports in some cases
// @ts-ignore
import type { RecentTransactionsTransactionsInner } from './recent-transactions-transactions-inner';

export interface RecentTransactions {
    'transactions'?: Array<RecentTransactionsTransactionsInner>;
    'summary'?: RecentTransactionsSummary;
}

