/* tslint:disable */
/* eslint-disable */
/**
 * NodeLabs API
 * A production-ready, fully modular Node.js Express boilerplate.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface RecentTransactionsTransactionsInner {
    'id'?: string;
    /**
     * Transaction name (product/service name)
     */
    'name'?: string;
    /**
     * Business/Company name
     */
    'business'?: string;
    /**
     * Business/Company logo URL
     */
    'image'?: string;
    /**
     * Transaction category
     */
    'type'?: string;
    /**
     * Transaction amount (positive for income, negative for expense)
     */
    'amount'?: number;
    'currency'?: string;
    'date'?: string;
    'status'?: RecentTransactionsTransactionsInnerStatusEnum;
}

export const RecentTransactionsTransactionsInnerStatusEnum = {
    Completed: 'completed',
    Pending: 'pending',
    Failed: 'failed'
} as const;

export type RecentTransactionsTransactionsInnerStatusEnum = typeof RecentTransactionsTransactionsInnerStatusEnum[keyof typeof RecentTransactionsTransactionsInnerStatusEnum];


