/* tslint:disable */
/* eslint-disable */
/**
 * NodeLabs API
 * A production-ready, fully modular Node.js Express boilerplate.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Note: The role field is NOT included in registration. All new users are automatically assigned the \"user\" role.
 */
export interface RegisterInput {
    /**
     * The user\'s full name.
     */
    'fullName': string;
    /**
     * The user\'s email address.
     */
    'email': string;
    /**
     * The user\'s password (must be at least 8 characters, with uppercase, lowercase, and a number).
     */
    'password': string;
}

