/* tslint:disable */
/* eslint-disable */
/**
 * NodeLabs API
 * A production-ready, fully modular Node.js Express boilerplate.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ScheduledTransfersTransfersInner {
    'id'?: string;
    /**
     * Recipient\'s full name
     */
    'name'?: string;
    /**
     * URL of the recipient\'s avatar/profile picture (generated from UI Avatars)
     */
    'image'?: string;
    /**
     * Scheduled date and time of the transfer
     */
    'date'?: string;
    /**
     * Transfer amount (negative for outgoing)
     */
    'amount'?: number;
    /**
     * Currency symbol or code
     */
    'currency'?: string;
    /**
     * Current status of the scheduled transfer
     */
    'status'?: ScheduledTransfersTransfersInnerStatusEnum;
}

export const ScheduledTransfersTransfersInnerStatusEnum = {
    Scheduled: 'scheduled',
    Processing: 'processing',
    Completed: 'completed',
    Cancelled: 'cancelled'
} as const;

export type ScheduledTransfersTransfersInnerStatusEnum = typeof ScheduledTransfersTransfersInnerStatusEnum[keyof typeof ScheduledTransfersTransfersInnerStatusEnum];


