/* tslint:disable */
/* eslint-disable */
/**
 * NodeLabs API
 * A production-ready, fully modular Node.js Express boilerplate.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ScheduledTransfersSummary } from './scheduled-transfers-summary';
// May contain unused imports in some cases
// @ts-ignore
import type { ScheduledTransfersTransfersInner } from './scheduled-transfers-transfers-inner';

export interface ScheduledTransfers {
    'transfers'?: Array<ScheduledTransfersTransfersInner>;
    'summary'?: ScheduledTransfersSummary;
}

