/* tslint:disable */
/* eslint-disable */
/**
 * NodeLabs API
 * A production-ready, fully modular Node.js Express boilerplate.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UserResponse {
    /**
     * The user\'s unique identifier.
     */
    'id'?: string;
    /**
     * The user\'s full name.
     */
    'fullName'?: string;
    /**
     * The user\'s email address.
     */
    'email'?: string;
    /**
     * The user\'s role (automatically set to \"user\" on registration, not sent in request).
     */
    'role'?: UserResponseRoleEnum;
    /**
     * Whether the user\'s account is active.
     */
    'isActive'?: boolean;
    /**
     * The date and time of the user\'s last login.
     */
    'lastLoginAt'?: string;
    /**
     * The IP address of the user\'s last login.
     */
    'lastLoginIP'?: string;
    /**
     * The date the user was created.
     */
    'createdAt'?: string;
    /**
     * The date the user was last updated.
     */
    'updatedAt'?: string;
}

export const UserResponseRoleEnum = {
    User: 'user',
    Admin: 'admin'
} as const;

export type UserResponseRoleEnum = typeof UserResponseRoleEnum[keyof typeof UserResponseRoleEnum];


