/* tslint:disable */
/* eslint-disable */
/**
 * NodeLabs API
 * A production-ready, fully modular Node.js Express boilerplate.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UsersLoginPost200ResponseData } from './users-login-post200-response-data';

export interface UsersLoginPost200Response {
    'success'?: boolean;
    'message'?: string;
    'data'?: UsersLoginPost200ResponseData;
}

