/* tslint:disable */
/* eslint-disable */
/**
 * NodeLabs API
 * A production-ready, fully modular Node.js Express boilerplate.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface WalletCardsInner {
    'id'?: string;
    'name'?: string;
    'type'?: WalletCardsInnerTypeEnum;
    /**
     * Full card number or masked number
     */
    'cardNumber'?: string;
    /**
     * Bank name with brand
     */
    'bank'?: string;
    'network'?: WalletCardsInnerNetworkEnum;
    'expiryMonth'?: number;
    'expiryYear'?: number;
    /**
     * Card color in hex format
     */
    'color'?: string;
    'isDefault'?: boolean;
}

export const WalletCardsInnerTypeEnum = {
    Credit: 'credit',
    Debit: 'debit'
} as const;

export type WalletCardsInnerTypeEnum = typeof WalletCardsInnerTypeEnum[keyof typeof WalletCardsInnerTypeEnum];
export const WalletCardsInnerNetworkEnum = {
    Visa: 'Visa',
    Mastercard: 'Mastercard',
    AmericanExpress: 'American Express'
} as const;

export type WalletCardsInnerNetworkEnum = typeof WalletCardsInnerNetworkEnum[keyof typeof WalletCardsInnerNetworkEnum];


