/* tslint:disable */
/* eslint-disable */
/**
 * NodeLabs API
 * A production-ready, fully modular Node.js Express boilerplate.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkingCapitalDataInner } from './working-capital-data-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkingCapitalSummary } from './working-capital-summary';

export interface WorkingCapital {
    'period'?: string;
    'currency'?: string;
    'data'?: Array<WorkingCapitalDataInner>;
    'summary'?: WorkingCapitalSummary;
}

