/* tslint:disable */
/* eslint-disable */
/**
 * NodeLabs API
 * A production-ready, fully modular Node.js Express boilerplate.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { FinancialSummaryGet200Response } from '../interfaces';
// @ts-ignore
import type { FinancialSummaryGet401Response } from '../interfaces';
// @ts-ignore
import type { FinancialSummaryGet500Response } from '../interfaces';
// @ts-ignore
import type { FinancialTransactionsRecentGet200Response } from '../interfaces';
// @ts-ignore
import type { FinancialTransfersScheduledGet200Response } from '../interfaces';
// @ts-ignore
import type { FinancialWalletGet200Response } from '../interfaces';
// @ts-ignore
import type { FinancialWorkingCapitalGet200Response } from '../interfaces';
/**
 * FinancialApi - axios parameter creator
 */
export const FinancialApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns total balance, total expenses, and total savings with change percentages.
         * @summary Get financial summary
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        financialSummaryGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/financial/summary`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns list of recent financial transactions.
         * @summary Get recent transactions
         * @param {number} [limit] Number of transactions to return (default 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        financialTransactionsRecentGet: async (limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/financial/transactions/recent`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns list of upcoming scheduled transfers with recipient details.
         * @summary Get scheduled transfers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        financialTransfersScheduledGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/financial/transfers/scheduled`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns list of credit/debit cards.
         * @summary Get wallet cards
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        financialWalletGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/financial/wallet`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns income and expense data for the last 6 months for chart visualization.
         * @summary Get working capital data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        financialWorkingCapitalGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/financial/working-capital`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FinancialApi - functional programming interface
 */
export const FinancialApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FinancialApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns total balance, total expenses, and total savings with change percentages.
         * @summary Get financial summary
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async financialSummaryGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinancialSummaryGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.financialSummaryGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FinancialApi.financialSummaryGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns list of recent financial transactions.
         * @summary Get recent transactions
         * @param {number} [limit] Number of transactions to return (default 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async financialTransactionsRecentGet(limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinancialTransactionsRecentGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.financialTransactionsRecentGet(limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FinancialApi.financialTransactionsRecentGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns list of upcoming scheduled transfers with recipient details.
         * @summary Get scheduled transfers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async financialTransfersScheduledGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinancialTransfersScheduledGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.financialTransfersScheduledGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FinancialApi.financialTransfersScheduledGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns list of credit/debit cards.
         * @summary Get wallet cards
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async financialWalletGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinancialWalletGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.financialWalletGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FinancialApi.financialWalletGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns income and expense data for the last 6 months for chart visualization.
         * @summary Get working capital data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async financialWorkingCapitalGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FinancialWorkingCapitalGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.financialWorkingCapitalGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FinancialApi.financialWorkingCapitalGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FinancialApi - factory interface
 */
export const FinancialApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FinancialApiFp(configuration)
    return {
        /**
         * Returns total balance, total expenses, and total savings with change percentages.
         * @summary Get financial summary
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        financialSummaryGet(options?: RawAxiosRequestConfig): AxiosPromise<FinancialSummaryGet200Response> {
            return localVarFp.financialSummaryGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns list of recent financial transactions.
         * @summary Get recent transactions
         * @param {FinancialApiFinancialTransactionsRecentGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        financialTransactionsRecentGet(requestParameters: FinancialApiFinancialTransactionsRecentGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<FinancialTransactionsRecentGet200Response> {
            return localVarFp.financialTransactionsRecentGet(requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns list of upcoming scheduled transfers with recipient details.
         * @summary Get scheduled transfers
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        financialTransfersScheduledGet(options?: RawAxiosRequestConfig): AxiosPromise<FinancialTransfersScheduledGet200Response> {
            return localVarFp.financialTransfersScheduledGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns list of credit/debit cards.
         * @summary Get wallet cards
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        financialWalletGet(options?: RawAxiosRequestConfig): AxiosPromise<FinancialWalletGet200Response> {
            return localVarFp.financialWalletGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns income and expense data for the last 6 months for chart visualization.
         * @summary Get working capital data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        financialWorkingCapitalGet(options?: RawAxiosRequestConfig): AxiosPromise<FinancialWorkingCapitalGet200Response> {
            return localVarFp.financialWorkingCapitalGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for financialTransactionsRecentGet operation in FinancialApi.
 */
export interface FinancialApiFinancialTransactionsRecentGetRequest {
    /**
     * Number of transactions to return (default 20)
     */
    readonly limit?: number
}

/**
 * FinancialApi - object-oriented interface
 */
export class FinancialApi extends BaseAPI {
    /**
     * Returns total balance, total expenses, and total savings with change percentages.
     * @summary Get financial summary
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public financialSummaryGet(options?: RawAxiosRequestConfig) {
        return FinancialApiFp(this.configuration).financialSummaryGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns list of recent financial transactions.
     * @summary Get recent transactions
     * @param {FinancialApiFinancialTransactionsRecentGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public financialTransactionsRecentGet(requestParameters: FinancialApiFinancialTransactionsRecentGetRequest = {}, options?: RawAxiosRequestConfig) {
        return FinancialApiFp(this.configuration).financialTransactionsRecentGet(requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns list of upcoming scheduled transfers with recipient details.
     * @summary Get scheduled transfers
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public financialTransfersScheduledGet(options?: RawAxiosRequestConfig) {
        return FinancialApiFp(this.configuration).financialTransfersScheduledGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns list of credit/debit cards.
     * @summary Get wallet cards
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public financialWalletGet(options?: RawAxiosRequestConfig) {
        return FinancialApiFp(this.configuration).financialWalletGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns income and expense data for the last 6 months for chart visualization.
     * @summary Get working capital data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public financialWorkingCapitalGet(options?: RawAxiosRequestConfig) {
        return FinancialApiFp(this.configuration).financialWorkingCapitalGet(options).then((request) => request(this.axios, this.basePath));
    }
}

