/* tslint:disable */
/* eslint-disable */
/**
 * NodeLabs API
 * A production-ready, fully modular Node.js Express boilerplate.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { LoginInput } from '../interfaces';
// @ts-ignore
import type { RegisterInput } from '../interfaces';
// @ts-ignore
import type { UserResponse } from '../interfaces';
// @ts-ignore
import type { UsersLoginPost200Response } from '../interfaces';
// @ts-ignore
import type { UsersLoginPost400Response } from '../interfaces';
// @ts-ignore
import type { UsersLoginPost401Response } from '../interfaces';
// @ts-ignore
import type { UsersLoginPost403Response } from '../interfaces';
// @ts-ignore
import type { UsersLoginPost429Response } from '../interfaces';
// @ts-ignore
import type { UsersRefreshTokenPost200Response } from '../interfaces';
// @ts-ignore
import type { UsersRegisterPost201Response } from '../interfaces';
/**
 * UserApi - axios parameter creator
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Logs in a user and returns an access token and a refresh token (in a cookie).
         * @summary Authenticate a user
         * @param {LoginInput} loginInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersLoginPost: async (loginInput: LoginInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginInput' is not null or undefined
            assertParamExists('usersLoginPost', 'loginInput', loginInput)
            const localVarPath = `/users/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Clears the refresh token cookie, effectively logging the user out.
         * @summary Log out the user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersLogoutPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the profile information of the currently authenticated user.
         * @summary Get current user\'s profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersProfileGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/profile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Uses the httpOnly refresh token cookie to issue a new access token.
         * @summary Refresh the access token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersRefreshTokenPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/refresh-token`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a new user account with role automatically set to \"user\".
         * @summary Register a new user
         * @param {RegisterInput} registerInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersRegisterPost: async (registerInput: RegisterInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registerInput' is not null or undefined
            assertParamExists('usersRegisterPost', 'registerInput', registerInput)
            const localVarPath = `/users/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * Logs in a user and returns an access token and a refresh token (in a cookie).
         * @summary Authenticate a user
         * @param {LoginInput} loginInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersLoginPost(loginInput: LoginInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsersLoginPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersLoginPost(loginInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersLoginPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Clears the refresh token cookie, effectively logging the user out.
         * @summary Log out the user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersLogoutPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersLogoutPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersLogoutPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves the profile information of the currently authenticated user.
         * @summary Get current user\'s profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersProfileGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersProfileGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersProfileGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Uses the httpOnly refresh token cookie to issue a new access token.
         * @summary Refresh the access token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersRefreshTokenPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsersRefreshTokenPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersRefreshTokenPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersRefreshTokenPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Creates a new user account with role automatically set to \"user\".
         * @summary Register a new user
         * @param {RegisterInput} registerInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersRegisterPost(registerInput: RegisterInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsersRegisterPost201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersRegisterPost(registerInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersRegisterPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * Logs in a user and returns an access token and a refresh token (in a cookie).
         * @summary Authenticate a user
         * @param {UserApiUsersLoginPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersLoginPost(requestParameters: UserApiUsersLoginPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<UsersLoginPost200Response> {
            return localVarFp.usersLoginPost(requestParameters.loginInput, options).then((request) => request(axios, basePath));
        },
        /**
         * Clears the refresh token cookie, effectively logging the user out.
         * @summary Log out the user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersLogoutPost(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.usersLogoutPost(options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves the profile information of the currently authenticated user.
         * @summary Get current user\'s profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersProfileGet(options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.usersProfileGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Uses the httpOnly refresh token cookie to issue a new access token.
         * @summary Refresh the access token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersRefreshTokenPost(options?: RawAxiosRequestConfig): AxiosPromise<UsersRefreshTokenPost200Response> {
            return localVarFp.usersRefreshTokenPost(options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a new user account with role automatically set to \"user\".
         * @summary Register a new user
         * @param {UserApiUsersRegisterPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersRegisterPost(requestParameters: UserApiUsersRegisterPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<UsersRegisterPost201Response> {
            return localVarFp.usersRegisterPost(requestParameters.registerInput, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for usersLoginPost operation in UserApi.
 */
export interface UserApiUsersLoginPostRequest {
    readonly loginInput: LoginInput
}

/**
 * Request parameters for usersRegisterPost operation in UserApi.
 */
export interface UserApiUsersRegisterPostRequest {
    readonly registerInput: RegisterInput
}

/**
 * UserApi - object-oriented interface
 */
export class UserApi extends BaseAPI {
    /**
     * Logs in a user and returns an access token and a refresh token (in a cookie).
     * @summary Authenticate a user
     * @param {UserApiUsersLoginPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersLoginPost(requestParameters: UserApiUsersLoginPostRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersLoginPost(requestParameters.loginInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Clears the refresh token cookie, effectively logging the user out.
     * @summary Log out the user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersLogoutPost(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersLogoutPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves the profile information of the currently authenticated user.
     * @summary Get current user\'s profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersProfileGet(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersProfileGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Uses the httpOnly refresh token cookie to issue a new access token.
     * @summary Refresh the access token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersRefreshTokenPost(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersRefreshTokenPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creates a new user account with role automatically set to \"user\".
     * @summary Register a new user
     * @param {UserApiUsersRegisterPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersRegisterPost(requestParameters: UserApiUsersRegisterPostRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersRegisterPost(requestParameters.registerInput, options).then((request) => request(this.axios, this.basePath));
    }
}

